#include<iostream>
#include "objeto.h"
#include "glm/glm.hpp"
#include "glm/ext.hpp"
#include "pecas.h"
#include"leitura.cpp"

Jogador iniciar_branco(){
    jogador branco;
    Objeto* torre_1 = ler_arquivo("tott.obj");
    Torre torre;
    torre.obj = torre_1;
    torre.translate = glm::vec3(15,1,0);
    branco.torres[0] = torre;
    Objeto* cavalo_1 = ler_arquivo("pawn3.obj");
    Cavalo cavalo;
    cavalo.obj = cavalo_1;
    cavalo.translate = glm::vec3(15,3,0);
    branco.cavalos[0] = cavalo;
    Objeto* bispo_1 = ler_arquivo("bispo.obj");
    Bispo bispo;
    bispo.obj = bispo_1;
    bispo.translate = glm::vec3(15,5,0);
    branco.bispos[0] = bispo;
    Objeto* rainha_ = ler_arquivo("rainha.obj");
    Rainha rainha;
    rainha.obj = rainha_;
    rainha.translate = glm::vec3(15,7,0);
    branco.rainha = rainha;
    Objeto* rei_ = ler_arquivo("rei.obj");
    Rei rei;
    rei.obj = rei_;
    rei.translate = glm::vec3(15,9,0);
    branco.rei = rei;
    Objeto* bispo_2 = ler_arquivo("pawn3.obj");
    bispo.obj = bispo_2;
    bispo.translate = glm::vec3(15,11,0);
    branco.bispos[1] = bispo;
    Objeto* cavalo_2 = ler_arquivo("pawn3.obj");
    cavalo.obj = cavalo_2;
    cavalo.translate = glm::vec3(15,13,0);
    branco.cavalos[1] = cavalo;
    Objeto* torre_2 = ler_arquivo("pawn3.obj");
    torre.obj = torre_2;
    torre.translate = glm::vec3(15,15,0);
    branco.torres[1] = torre;
    Objeto* peao_1 = ler_arquivo("pawn3.obj");
    Peao peao;
    peao.obj = peao_1;
    peao.translate = glm::vec3(13,1,0);
    branco.peoes[0] = peao;
    Objeto* peao_2 = ler_arquivo("pawn3.obj");
    peao.obj = peao_2;
    peao.translate = glm::vec3(13,3,0);
    branco.peoes[1] = peao;
    Objeto* peao_3 = ler_arquivo("pawn3.obj");
    peao.obj = peao_3;
    peao.translate = glm::vec3(13,5,0);
    branco.peoes[2] = peao;
    Objeto* peao_4 = ler_arquivo("pawn3.obj");
    peao.obj = peao_4;
    peao.translate = glm::vec3(13,7,0);
    branco.peoes[3] = peao;
    Objeto* peao_5 = ler_arquivo("pawn3.obj");
    peao.obj = peao_5;
    peao.translate = glm::vec3(13,9,0);
    branco.peoes[4] = peao;
    Objeto* peao_6 = ler_arquivo("pawn3.obj");
    peao.obj = peao_6;
    peao.translate = glm::vec3(13,11,0);
    branco.peoes[5] = peao;
    Objeto* peao_7 = ler_arquivo("pawn3.obj");
    peao.obj = peao_7;
    peao.translate = glm::vec3(13,13,0);
    branco.peoes[6] = peao;
    Objeto* peao_8 = ler_arquivo("pawn3.obj");
    peao.obj = peao_8;
    peao.translate = glm::vec3(13,15,0);
    branco.peoes[7] = peao;
    return branco;
}
Jogador iniciar_preto(){
    jogador preto;
    Objeto* torre_1 = ler_arquivo("pawn3.obj");
    Torre torre;
    torre.obj = torre_1;
    torre.translate = glm::vec3(1,1,0);
    preto.torres[0] = torre;
    Objeto* cavalo_1 = ler_arquivo("pawn3.obj");
    Cavalo cavalo;
    cavalo.obj = cavalo_1;
    cavalo.translate = glm::vec3(1,3,0);
    preto.cavalos[0] = cavalo;
    Objeto* bispo_1 = ler_arquivo("pawn3.obj");
    Bispo bispo;
    bispo.obj = bispo_1;
    bispo.translate = glm::vec3(1,5,0);
    preto.bispos[0] = bispo;
    Objeto* rainha_ = ler_arquivo("pawn3.obj");
    Rainha rainha;
    rainha.obj = rainha_;
    rainha.translate = glm::vec3(1,7,0);
    preto.rainha = rainha;
    Objeto* rei_ = ler_arquivo("pawn3.obj");
    Rei rei;
    rei.obj = rei_;
    rei.translate = glm::vec3(1,9,0);
    preto.rei = rei;
    Objeto* bispo_2 = ler_arquivo("pawn3.obj");
    bispo.obj = bispo_2;
    bispo.translate = glm::vec3(1,11,0);
    preto.bispos[1] = bispo;
    Objeto* cavalo_2 = ler_arquivo("pawn3.obj");
    cavalo.obj = cavalo_2;
    cavalo.translate = glm::vec3(1,13,0);
    preto.cavalos[1] = cavalo;
    Objeto* torre_2 = ler_arquivo("pawn3.obj");
    torre.obj = torre_2;
    torre.translate = glm::vec3(1,15,0);
    preto.torres[1] = torre;
    Objeto* peao_1 = ler_arquivo("pawn3.obj");
    Peao peao;
    peao.obj = peao_1;
    peao.translate = glm::vec3(3,1,0);
    preto.peoes[0] = peao;
    Objeto* peao_2 = ler_arquivo("pawn3.obj");
    peao.obj = peao_2;
    peao.translate = glm::vec3(3,3,0);
    preto.peoes[1] = peao;
    Objeto* peao_3 = ler_arquivo("pawn3.obj");
    peao.obj = peao_3;
    peao.translate = glm::vec3(3,5,0);
    preto.peoes[2] = peao;
    Objeto* peao_4 = ler_arquivo("pawn3.obj");
    peao.obj = peao_4;
    peao.translate = glm::vec3(3,7,0);
    preto.peoes[3] = peao;
    Objeto* peao_5 = ler_arquivo("pawn3.obj");
    peao.obj = peao_5;
    peao.translate = glm::vec3(3,9,0);
    preto.peoes[4] = peao;
    Objeto* peao_6 = ler_arquivo("pawn3.obj");
    peao.obj = peao_6;
    peao.translate = glm::vec3(3,11,0);
    preto.peoes[5] = peao;
    Objeto* peao_7 = ler_arquivo("pawn3.obj");
    peao.obj = peao_7;
    peao.translate = glm::vec3(3,13,0);
    preto.peoes[6] = peao;
    Objeto* peao_8 = ler_arquivo("pawn3.obj");
    peao.obj = peao_8;
    peao.translate = glm::vec3(3,15,0);
    preto.peoes[7] = peao;
    return preto;
}
